const readline=require('readline-sync');
let y= ['adjective'];
let f= ['feelings'];
let p= ['place'];
let n= ['noun'];
let v= ['verb'];
let o= ['plural noun'];
let e= ['emotion'];

let word= readline.question(`${y}:`);
let word2= readline.question(`${y}:`);
let word3= readline.question(`${p}:`);
let word4= readline.question(`${f}:`);
let word5= readline.question(`${p}:`);
let word6= readline.question(`${e}:`);
let word7= readline.question(`${y}:`);
let word8= readline.question(`${y}:`);
let word9= readline.question(`${y}:`);
let word10= readline.question(`${y}:`);
let word11= readline.question(`${n}:`);
let word12= readline.question(`${y}:`);
let word13= readline.question(`${y}:`);
let word14= readline.question(`${o}:`);
let word15= readline.question(`${y}:`);
let word16= readline.question(`${v}`);
let word17= readline.question(`${n}:`);
let word18= readline.question(`${n}:`);
let word19= readline.question(`${y}:`);
let word20= readline.question(`${p}:`);

console.log(`There was once a ${word}, ${word2} place called ${word3}. People of many different ${word4} are around there like ${word5}. Even if you are ${word6}, you will have a great time at this ${word7}, ${word8} place, even if this place is ${word9} and ${word10} in this place full of ${word11}. No matter how ${word12} and ${word13} the ${word14} are it will remain ${word15}. At the ${word16} this place has many kind ${word17} and ${word18} from the affable${word19} environment unlike ${word20}.` );